### ISSUE TITLE
Peer Dependency: react-docgen

### ISSUE THREAD

**Issue by sem4phor** [nerdlabs/react-docgen-displayname-handler#10]
Hi cpould you please update the version of the peer dependency react-docgen? 4.1.1 is the latest release and current beta is 5.0.0.

There are currently warnings in vue-styleguidist and i belive in react-styleguidist, too.

Thanks in advance.

**Comment by ZauberNerd** [comment]
Sorry for the delay. I've released a new version: [v2.1.2](https://github.com/nerdlabs/react-docgen-displayname-handler/releases/tag/v2.1.2)
