### ISSUE TITLE
Vesion bump required for dependencies 

### ISSUE THREAD

**Issue by pasupuletics** [nerdlabs/react-docgen-displayname-handler#2]
@ZauberNerd , Could you please update the dependencies to latest versions(recast, react-docgen), with the current versions of react-docgen custom handlers are breaking which are using for react-styleguidist.

@sapegin , @zined

**Comment by LotharSee** [comment]
Same problem here, and that breaks the last versions of `react-styleguidist`.

**Comment by sapegin** [comment]
@ZauberNerd Could you please publish a new version to npm?

**Comment by ZauberNerd** [comment]
Published as 1.0.1
